name = "custom-tmux-conf"
tmux_options = "-f /tmp/tmux.override.conf -f /tmp/tmux.override-2.conf"

[[windows]]
  name = "one"
  [[windows.panes]]
  commands = ["echo window-on--pane-one"]

[[windows]]
  name = "two"
  [[windows.panes]]
  commands = ["echo window-two-pane-one"]

